### PR TITLE
Merge to NoBouncyCastle from Master (2018-03-04)

### PR DESCRIPTION
**Pull request by linuxwolf**

### CODE REVIEW

**Comment by jimsch** [comment]
Is this just picking up the changes that I made to the master but not to this branch?

**Comment by linuxwolf** [comment]
> Is this just picking up the changes that I made to the master but not to this branch?

for the contents of the PR, that is correct.  This also testing if I had the ability to write to this branch without actually pushing new commits; I thought having write access to a branch would also allow clicking "merge" on a PR for that branch, but it does not appear to be the case.

**Comment by jimsch** [comment]
I am still seeing you as pending for the NoBC team.

**Comment by linuxwolf** [comment]
hrm ... I don't see a request to join in my (email | github) inbox ...

**Comment by jimsch** [comment]
Ok - Lynx is not Linux.

**Comment by jimsch** [comment]
Did that give you merge?

**Comment by linuxwolf** [comment]
That did it.

Thanks @jimsch.

**Pull request merged**
